### ISSUE TITLE
Add fl-server frontend

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/rfs#67]
We need to support a frontend for `flist server` 

- https://github.com/threefoldtech/rfs/issues/61

### Pages

- [x] `login page`: we should add a page to allow the user to log in and save the token generated (jwt token)
- [x] `create flist page`: we should support a page to create a flist with its requirements (needs to apply valiadations)
- [x] `follow up on flist creation page`: we should support a page to follow up the progress for a flist (maybe it should be integrated with the previous one
- [x] `list flists page`: we should support listing different flists for each username exists (public no auth needed)
- [x] `preview flist page`: we should support previewing flist (public no auth needed)

### Requirements

- [x] a good UI should be provided before starting the frontend part
- [x] Use `vue 3` in frontend implementation

> **NOTE:**  The api is available using  [swagger.json](https://github.com/user-attachments/files/16414340/swagger.json)
when running the server

**Comment by ehab-hassan** [comment]
Login page with logo
https://www.figma.com/proto/pRMxGO2AIjWlofvUSJH0Dn/RFS?node-id=2-240&t=eIGAIRtZRB8W1g2q-0&scaling=contain&content-scaling=fixed&page-id=0%3A1

**Comment by ehab-hassan** [comment]
all 4 pages are updated here
https://www.figma.com/proto/pRMxGO2AIjWlofvUSJH0Dn/RFS?node-id=119-196&t=B4PK7xwM2ZcG6qom-0&scaling=contain&content-scaling=fixed&page-id=0%3A1
- Home (without sign in)
- Sign in
- User page when sign in
- Create a flist page

**Comment by ehab-hassan** [comment]
The theme changed to be like a dashboard

https://www.figma.com/proto/pRMxGO2AIjWlofvUSJH0Dn/RFS?node-id=119-196&t=5Q84f9sPQjfRicBC-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=119%3A196

there is one page to show dark mode when you click light/dark mode

use this image for login and home
![rfs_login](https://github.com/user-attachments/assets/a23c63a5-afc7-4352-9755-d5a70cdd19a0)
![rfs_home](https://github.com/user-attachments/assets/a55325e1-687c-4d4b-8a34-a6e3bfa74008)

**Comment by ehab-hassan** [comment]
preview page
https://www.figma.com/proto/pRMxGO2AIjWlofvUSJH0Dn/RFS?node-id=403-266&t=uvaxUKXWMClLp8PR-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=119%3A196

**Comment by ashraffouda** [comment]
applied the steps here 
https://github.com/threefoldtech/rfs/tree/master/frontend
logged in  and created two flists from create flist page 
![image](https://github.com/user-attachments/assets/fc980bc6-962d-4f02-8691-2107a16e1a94)
and I was able to list and view them
flist list page 
![image](https://github.com/user-attachments/assets/4ca1b791-f483-4230-9efb-19bd47076003)

![image](https://github.com/user-attachments/assets/d61ec67f-a244-40a6-9b39-bf26dcf31c88)
