### ISSUE TITLE
Create new testsuite to cover rfs on Testlodge

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/rfs#73]
we need to add test cases from scratch on testlodge to cover all the rfs features.
Docs: https://github.com/threefoldtech/rfs

**Comment by khaledyoussef24** [comment]
currently reviewing the created test suite and fixing some test cases
and started to create the missing sections for parts which was not covered
[testsuite](https://app.testlodge.com/a/26076/projects/40893/suites/244349)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
please add estimate

**Comment by khaledyoussef24** [comment]
finished creating the test suite and testing only will try to create the flist on zdb machine today

[RFS testsuite](https://app.testlodge.com/a/26076/projects/40893/suites/244349)

**Comment by khaledyoussef24** [comment]
finished creating the test suite and testing only will try to create the flist on zdb machine today

[RFS testsuite](https://app.testlodge.com/a/26076/projects/40893/suites/244349)

**Comment by khaledyoussef24** [comment]
created an flist on zdb and created [test section](https://app.testlodge.com/a/26076/projects/40893/suites/244349?expand_section=452446#suite_section_452446) for it on test lodge
