### ISSUE TITLE
Broken link on docs

### ISSUE THREAD

**Issue by Marinaa-Emad** [threefoldtech/rfs#74]
New found a broken link: https://github.com/threefoldtech/rfs/blob/master/schema/schema.sql.
![Screenshot from 2024-08-20 15-42-52](https://github.com/user-attachments/assets/931d4816-e90d-43e0-b5f4-9c6b27ac07de)

**Comment by rawdaGastan** [comment]
The working one: `https://github.com/threefoldtech/rfs/blob/master/rfs/schema/schema.sql`
