### ISSUE TITLE
Rfs supporting macos

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/rfs#78]
will be there any version of rfs supporting macos ?

**Comment by iwanbk** [comment]
> will be there any version of rfs supporting macos ?

do we have usecase for this?
If yes, i will be happy to take it.

**Comment by ramezsaeed** [comment]
@iwanbk 
Yes we need this one.

**Comment by iwanbk** [comment]
Hi @ramezsaeed 
I can make it compiled, do you have simple flist for testing?

**Comment by iwanbk** [comment]
got issue when trying to create `.fl` from Redis docker image, tracked at #79
