### ISSUE TITLE
add macos support

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/rfs#81]
Creating new issue to replace #78.
Split the work into several tasks:
- [ ] `docker2fl` on macos #82
- [ ] github actions workflow #82
- [ ] `rfs` on macos

**Comment by iwanbk** [comment]
I found that `polyfuse`, the `fuse` library used by `rfs` only supports Linux.
So, adding macos support to `rfs` wouldn't be trivial,  unlike the `docker2fl`.
Will do it on separate PR.

**Comment by xmonader** [comment]
@iwanbk what is the reason to do this one?

**Comment by iwanbk** [comment]
@xmonader the reason are:
-  this https://github.com/threefoldtech/rfs/issues/78#issuecomment-2413461220
- and #78 also included in 3.16

(and i have some free time yesterday)

Let me know if i misunderstood it before i'm going too far.

**Comment by xmonader** [comment]
For now, there's no plan to support RFS on OSX not on our priority list not for 3.15 nor for 3.16

**Comment by iwanbk** [comment]
ok
